media:
  input: docs/media
  output: media
content:
  - name: projects
    label: Projects
    path: docs/_projects
    type: collection
    fields:
      - name: title
        label: Title
        type: text
        options:
          maxlength: 140
      - name: role
        label: Roles
        type: text
        options:
          maxlength: 140
      - name: description
        label: Description
        type: text
      - name: category
        label: Category
        type: select
        options:
          values: [ Documentary, Product Videos, After Movies, Coorperate Videos, Others ]
      - name: images
        label: Images
        type: image
        list: true
      - name: slug
        label: Slug
        type: text
        options:
          maxlength: 20
      - name: video
        label: Video
        type: text
  - name: blogs
    label: Blogs
    path: docs/_blogs
    type: collection
    fields:
      - name: title
        label: Title
        type: text
        options:
          maxlength: 140
      - name: cover
        label: Cover
        type: image
      - name: content
        label: Content
        type: rich-text
  - name: site
    label: Site settings
    path: docs/site.json
    type: file
    fields:
      - name: title
        label: Website title
        type: string
      - name: description
        label: Website description
        type: string
        description: Will be provused for any page with no description.
      - name: url
        label: Website URL
        type: string
        pattern: ^(https?:\/\/)?(www\.)?[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}(\/[^\s]*)?$
      - name: cover
        label: Preview image
        type: image
        description: Image used in the social preview on social networks (e.g. Facebook, Twitter...)