name: Convert Markdown Files to JSON

on:
  push:
    branches: [ main ]

jobs:
  markdown-to-json:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Markdown to JSON
      uses: ClydeDz/markdown-to-json@v0.1.0
      with:
        settings-json-file: docs/_data/mds2json.json

    # Commit all changed files back to the repository
    - uses: stefanzweifel/git-auto-commit-action@v5
      with:
          commit_message: Apply converted files
