name: Resize images

on: 
  push:
      branches: [ main ]
      # Check if imgs, config files pushed only
      paths:
        - 'docs/media/**/*.jpg'
        - 'docs/media/**/*.jpeg'
        - 'docs/media/**/*.png'
        - '**/resizeImgs.yml'

jobs:
  build:
    name: Github Action Image Resizing
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v4

      - name: Resize Images
        id: resize-images

        # You can change the version as well
        uses: gonzalonaveira/gh-image-resizing@master
        with:
          IMAGES_MAX_WIDTH: "1024"
          IMAGES_QUALITY: "85"
          IMAGES_FORMATS: "jpg, jpeg, png" 
          IMAGES_DIRECTORIES: "docs/media/gallery"
          IMAGES_SUFFIX: "_md"
          DEBUG: True

      - name: Commit changes
        uses: EndBug/add-and-commit@v4
        with:
          add: 'docs/media'
          author_name: "github-actions[bot]"
          author_email: "github-actions@users.noreply.github.com"
          message: |
            Images Reszied by Github action
            ${{steps.resize-images.outputs.result}}
